version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: metric_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metric-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:


networks:
  postgres_network:
    driver: bridge