version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: 'metric-redis'
    ports:
      - '6379:6379'
    volumes:
      - ./.docker/db/redis:/data/db
    networks:
      - metrics-net
  postgres:
    image: postgres:latest
    container_name: metric-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metric-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metrics-net

volumes:
  postgres_data:


networks:
  metrics-net:
    driver: bridge
